2018-04-02 18:14:02,763[ WARN] An unexpected connection driver error occured (Exception message: Connection reset) --- com.rabbitmq.client.impl.ForgivingExceptionHandler.log(ForgivingExceptionHandler.java:115) AMQP Connection 192.168.1.201:5672
2018-04-02 18:14:02,712[ WARN] Error during reading frames --- com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:169) rabbitmq-nio
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_151]
	at com.rabbitmq.client.impl.nio.NioHelper.read(NioHelper.java:25) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.prepareForReadSequence(SocketChannelFrameHandlerState.java:185) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:143) [amqp-client-5.1.2.jar:5.1.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2018-04-02 18:14:02,718[ WARN] Error during reading frames --- com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:169) rabbitmq-nio
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_151]
	at com.rabbitmq.client.impl.nio.NioHelper.read(NioHelper.java:25) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.prepareForReadSequence(SocketChannelFrameHandlerState.java:185) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:143) [amqp-client-5.1.2.jar:5.1.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2018-04-02 18:14:03,077[ERROR] An unexpected connection driver error occured --- com.rabbitmq.client.impl.ForgivingExceptionHandler.log(ForgivingExceptionHandler.java:119) rabbitmq-connection-shutdown-amqp://guest@192.168.1.201:5672/
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_151]
	at com.rabbitmq.client.impl.nio.NioHelper.read(NioHelper.java:25) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.prepareForReadSequence(SocketChannelFrameHandlerState.java:185) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:143) ~[amqp-client-5.1.2.jar:5.1.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2018-04-02 18:14:02,985[ERROR] Channel shutdown: connection error --- org.springframework.amqp.rabbit.connection.CachingConnectionFactory$DefaultChannelCloseLogger.log(CachingConnectionFactory.java:1292) AMQP Connection 192.168.1.201:5672
2018-04-02 18:14:03,111[ERROR] An unexpected connection driver error occured --- com.rabbitmq.client.impl.ForgivingExceptionHandler.log(ForgivingExceptionHandler.java:119) rabbitmq-connection-shutdown-amqp://guest@192.168.1.201:5672/
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_151]
	at com.rabbitmq.client.impl.nio.NioHelper.read(NioHelper.java:25) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.prepareForReadSequence(SocketChannelFrameHandlerState.java:185) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:143) ~[amqp-client-5.1.2.jar:5.1.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2018-04-02 18:14:06,383[ WARN] No URLs will be polled as dynamic configuration sources. --- com.netflix.config.sources.URLConfigurationSource.<init>(URLConfigurationSource.java:121) RMI TCP Connection(2)-127.0.0.1
2018-04-02 18:14:13,188[ERROR] Caught an exception during connection recovery! --- com.rabbitmq.client.impl.ForgivingExceptionHandler.log(ForgivingExceptionHandler.java:119) rabbitmq-connection-shutdown-amqp://guest@192.168.1.201:5672/
java.net.NoRouteToHostException: No route to host: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:1.8.0_151]
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerFactory.create(SocketChannelFrameHandlerFactory.java:87) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConnection(AutorecoveringConnection.java:550) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:512) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$2.recoveryCanBegin(AutorecoveringConnection.java:453) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.AMQConnection.handleIoError(AMQConnection.java:672) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.NioLoop.lambda$dispatchIoErrorToConnection$0(NioLoop.java:275) ~[amqp-client-5.1.2.jar:5.1.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2018-04-02 18:14:13,530[ERROR] Caught an exception during connection recovery! --- com.rabbitmq.client.impl.ForgivingExceptionHandler.log(ForgivingExceptionHandler.java:119) rabbitmq-connection-shutdown-amqp://guest@192.168.1.201:5672/
java.net.NoRouteToHostException: No route to host: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:1.8.0_151]
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerFactory.create(SocketChannelFrameHandlerFactory.java:87) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConnection(AutorecoveringConnection.java:550) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:512) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$2.recoveryCanBegin(AutorecoveringConnection.java:453) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.AMQConnection.handleIoError(AMQConnection.java:672) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.nio.NioLoop.lambda$dispatchIoErrorToConnection$0(NioLoop.java:275) ~[amqp-client-5.1.2.jar:5.1.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
